# Generated by Django 5.2.15 on 2026-06-12 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('cow_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('breed', models.CharField(default='White Fulani', max_length=50)),
                ('herd_id', models.CharField(default='Herd_A', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_activity', models.FloatField(default=50.0)),
                ('baseline_rumination', models.FloatField(default=30.0)),
                ('baseline_lying_time', models.FloatField(default=70.0)),
                ('baseline_temp', models.FloatField(default=38.5)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('source_type', models.CharField(choices=[('synthetic', 'Synthetic (Literature-Calibrated)'), ('public', 'Public (Validation Dataset)')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=30)),
                ('risk_score', models.FloatField()),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.cow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosed_trait', models.CharField(max_length=30)),
                ('is_confirmed', models.BooleanField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='core.alert')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('trait', models.CharField(max_length=30)),
                ('score', models.FloatField()),
                ('label', models.IntegerField()),
                ('feature_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shap_values', models.JSONField()),
                ('human_readable_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='core.prediction')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.prediction'),
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trait', models.CharField(choices=[('estrus', 'Estrus'), ('mastitis_risk', 'Subclinical Mastitis Risk'), ('heat_stress', 'Heat Stress'), ('calving_imminent', 'Calving Imminent')], max_length=30)),
                ('family', models.CharField(choices=[('interpretable', 'Interpretable Model'), ('black_box', 'Black-Box Model')], max_length=20)),
                ('algorithm', models.CharField(max_length=50)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('model_file_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainedmodel'),
        ),
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('features', models.JSONField()),
                ('labels', models.JSONField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_sets', to='core.cow')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_sets', to='core.dataset')),
            ],
            options={
                'indexes': [models.Index(fields=['cow', 'timestamp'], name='core_featur_cow_id_f53c0b_idx'), models.Index(fields=['dataset', 'timestamp'], name='core_featur_dataset_b40614_idx')],
                'unique_together': {('cow', 'dataset', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='RawSensorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('activity_index', models.FloatField()),
                ('step_count', models.IntegerField()),
                ('rumination_min', models.FloatField()),
                ('lying_time_min', models.FloatField()),
                ('body_temp_c', models.FloatField()),
                ('ambient_temp_c', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('milk_yield', models.FloatField(blank=True, null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_sensor_records', to='core.cow')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_sensor_records', to='core.dataset')),
            ],
            options={
                'indexes': [models.Index(fields=['cow', 'timestamp'], name='core_rawsen_cow_id_60eb6e_idx'), models.Index(fields=['dataset', 'timestamp'], name='core_rawsen_dataset_b18bac_idx')],
                'unique_together': {('cow', 'dataset', 'timestamp')},
            },
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['cow', 'timestamp'], name='core_predic_cow_id_d6f707_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['trait'], name='core_predic_trait_94cb98_idx'),
        ),
    ]
